//
//  MessagesViewController.swift
//  qt MessagesExtension
//
//  Created by ivin on 2/10/26.
//

import UIKit
import Messages
import SwiftUI
import QtUI

@MainActor
final class MessagesViewController: MSMessagesAppViewController {
    private var hostingController: UIHostingController<AnyView>?
    private var host: MessagesHost!
    private var selectedMessageURL: URL?

    override func viewDidLoad() {
        super.viewDidLoad()
        host = MessagesHost(controller: self)
        hostSwiftUIView()
    }

    private func hostSwiftUIView() {
        // Build the injected actions
        let actions = MessagesActions(
            requestExpanded: { [weak host] in host?.requestExpanded() },
            requestCompact: { [weak host] in host?.requestCompact() },
            insertText: { [weak host] text in host?.insertText(text) },
            insertEventLink: { [weak host] url, title in host?.insertEventLink(url, title: title) }
        )

        let root = ContentView(selectedMessageURL: selectedMessageURL)
            .environment(\.messagesActions, actions)

        if let hc = hostingController {
            hc.rootView = AnyView(root)
            return
        }

        let hc = UIHostingController(rootView: AnyView(root))
        addChild(hc)
        view.addSubview(hc.view)

        hc.view.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            hc.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            hc.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            hc.view.topAnchor.constraint(equalTo: view.topAnchor),
            hc.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        ])

        hc.didMove(toParent: self)
        hostingController = hc
    }

    private func refreshUI() {
        hostSwiftUIView()
    }

    private func syncSelection(from conversation: MSConversation?) {
        selectedMessageURL = eventURL(from: conversation?.selectedMessage)
    }

    private func isEventURL(_ url: URL?) -> Bool {
        guard let url else { return false }
        guard url.scheme == "qt" else { return false }
        if url.host == "event" { return true }
        if url.pathComponents.contains("event") { return true }
        return url.absoluteString.hasPrefix("qt:event")
    }

    private func eventURL(from message: MSMessage?) -> URL? {
        guard let message else { return nil }

        if isEventURL(message.url) {
            return message.url
        }

        if let summaryText = message.summaryText,
           let encodedURL = EncodedEventURL.unpack(summaryText),
           isEventURL(encodedURL) {
            return encodedURL
        }

        if let summaryText = message.summaryText,
           let parsed = URL(string: summaryText),
           isEventURL(parsed) {
            return parsed
        }

        if let layout = message.layout as? MSMessageTemplateLayout,
           let subcaption = layout.subcaption,
           let encodedURL = EncodedEventURL.unpack(subcaption),
           isEventURL(encodedURL) {
            return encodedURL
        }

        if let layout = message.layout as? MSMessageTemplateLayout,
           let subcaption = layout.subcaption,
           let parsed = URL(string: subcaption),
           isEventURL(parsed) {
            return parsed
        }

        return nil
    }

    private func updatePresentationForSelection() {
        if isEventURL(selectedMessageURL) {
            host.requestExpanded()
        }
    }

    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.

        // Use this method to configure the extension and restore previously stored state.
        super.willBecomeActive(with: conversation)
        host.updateConversation(conversation)
        syncSelection(from: conversation)
        updatePresentationForSelection()
        refreshUI()
        print("willBecomeActive")
    }

    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.

        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
        super.didResignActive(with: conversation)
        host.updateConversation(nil)
        selectedMessageURL = nil
        print("didResignActive")
    }

    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.

        // Use this method to trigger UI updates in response to the message.
        selectedMessageURL = eventURL(from: message) ?? eventURL(from: conversation.selectedMessage) ?? selectedMessageURL
        updatePresentationForSelection()
        refreshUI()
        print("didReceive")
    }

    override func didSelect(_ message: MSMessage, conversation: MSConversation) {
        selectedMessageURL = eventURL(from: message) ?? eventURL(from: conversation.selectedMessage)
        updatePresentationForSelection()
        refreshUI()
    }

    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
        print("didStartSending")
    }

    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.

        // Use this to clean up state related to the deleted message.
        print("didCancelSending")
    }

    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.

        // Use this method to prepare for the change in presentation style.
        print("willTransition")
    }

    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.

        // Use this method to finalize any behaviors associated with the change in presentation style.
        syncSelection(from: activeConversation)
        updatePresentationForSelection()
        refreshUI()
        print("didTransition")
    }

}

private enum EncodedEventURL {
    private static let lead = "\u{2063}"
    private static let zero = "\u{200B}"
    private static let one = "\u{200C}"

    static func unpack(_ text: String) -> URL? {
        guard let range = text.range(of: lead) else { return nil }
        let payload = String(text[range.upperBound...])
        guard !payload.isEmpty else { return nil }

        var bits: [UInt8] = []
        bits.reserveCapacity(payload.count)
        for scalar in payload.unicodeScalars {
            if String(scalar) == zero {
                bits.append(0)
            } else if String(scalar) == one {
                bits.append(1)
            }
        }

        guard bits.count >= 8 else { return nil }
        let usableBitCount = bits.count - (bits.count % 8)
        guard usableBitCount > 0 else { return nil }

        var bytes: [UInt8] = []
        bytes.reserveCapacity(usableBitCount / 8)
        var index = 0
        while index < usableBitCount {
            var value: UInt8 = 0
            for bitOffset in 0..<8 {
                value = (value << 1) | bits[index + bitOffset]
            }
            bytes.append(value)
            index += 8
        }

        guard let raw = String(bytes: bytes, encoding: .utf8) else { return nil }
        return URL(string: raw)
    }
}
