//
//  MessagesViewController.swift
//  qt MessagesExtension
//
//  Created by ivin on 2/10/26.
//

import UIKit
import Messages
import SwiftUI
import QtUI

@MainActor
final class MessagesViewController: MSMessagesAppViewController {
    private var hostingController: UIHostingController<AnyView>?
    private var host: MessagesHost!

    override func viewDidLoad() {
        super.viewDidLoad()
        host = MessagesHost(controller: self)
        hostSwiftUIView()
    }

    private func hostSwiftUIView() {
        guard hostingController == nil else { return }

        // Build the injected actions
        let actions = MessagesActions(
            requestExpanded: { [weak host] in host?.requestExpanded() },
            requestCompact: { [weak host] in host?.requestCompact() },
            insertText: { [weak host] text in host?.insertText(text) },
            insertEventLink: { [weak host] url, title in host?.insertEventLink(url, title: title) }
        )

        let root = ContentView() // from your package
            .environment(\.messagesActions, actions)

        let hc = UIHostingController(rootView: AnyView(root))
        addChild(hc)
        view.addSubview(hc.view)

        hc.view.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            hc.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            hc.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            hc.view.topAnchor.constraint(equalTo: view.topAnchor),
            hc.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        ])

        hc.didMove(toParent: self)
        hostingController = hc
    }
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
        super.willBecomeActive(with: conversation)
        host.updateConversation(conversation)
        print("willBecomeActive")
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
        super.didResignActive(with: conversation)
        host.updateConversation(nil)
        print("didResignActive")
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
        print("didReceive")
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
        print("didStartSending")
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
        print("didCancelSending")
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
        print("willTransition")
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
        print("didTransition")
    }

}
