// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "qt-playground",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "qt-playground",
            targets: ["AppModule"],
            bundleIdentifier: "com.ivinn.qt-playground",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(path: "../qt MessagesExtension/QtUI")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "QtUI", package: "QtUI")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)